version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/storyforest-server

permissions:
  - object: scripts/start-server.sh
    mode: 755
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu
